project:
  type: website
  render:
    - index.qmd 
    - report.qmd
    - ideas.qmd

website:
  title: "Transforming Strategic Active Travel Network Planning Internationally"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: report.qmd
      - text: "Ideas"
        href: ideas.qmd 
